name: country_picker
description: Custom version of country_picker
version: 2.0.27
# homepage: https://yourdomain.dev

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
